### PR TITLE
Moved to flask, updated documentation and added needed crossdomain.xml

### PR DESCRIPTION
**Pull request by JordanPlayz158**
Moved to flask as the current http implementation is a bit difficult to work with and presented some problems and flask seems nicer to work with. Updated documentation due to added dependencies and different run commands.  Added crossdomain.xml as it is required for normal flash player to work.

### CODE REVIEW

**Comment by etrotta** [comment]
Some issues:
- Must keep support for 3.9 (no match/case statement)
- Must have a main.py file with an app variable in it (how deta deployment works)

**Comment by etrotta** [comment]
After getting it running on deta space, it looks like the Adobe flash player / debugger is not satisfied with it:

```
Error #2044: Unhandled securityError:. text=Error #2170: Security sandbox violation: file:///C|/Users/.../PTD/PTD3%5Fdeta%5Fspace.swf cannot send HTTP headers to https://ptd3server-1-o2189185.deta.app/ptd3save/etrotta?Date=1678225450780.
	at code.sndgames.ptd3.screens::screen_Main/pressed_Load_Account()
	at code.sndgames.ptd3.screens::screen_Main/mouse_Up_Screen()
	at code.sndgames.game_template.baseCode::gameObj_Screen/mouse_Up()
	at code.sndgames.ptd3.main::main/mouse_Up()
```

**Comment by JordanPlayz158** [comment]
I didn't test on deta but on local it should work fine, but I think I know the fix for deta.

**Comment by JordanPlayz158** [comment]
Should be fixed on deta

**Pull request merged**
